openapi: 3.0.0
info:
  version: 0.0-oas3
  title: cpuinfo
  description: >-
    A simple service to get cpuinfo as an example of using swagger-2.0
    specification and codegen
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Cloudmesh REST Service Example
  license:
    name: Apache
paths:
  /file/<filename>:
    post:
      tags:
        - Upload
      summary: Upload a file 
      operationId: file.upload
      parameters:
        - name: filename
          in: query
          description: filename to be uploaded 
          required: true
          schema:
            type: string 
      responses:
        '405':
          description: Invalid input
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
    get:
      tags:
        - Download
      summary: Download a file
      operationId: file.download
      responses:
        '405':
          description: Invalid input
  /list:
    get:
      tags:
        - List 
      operationId: file.list_files
      description: Returns cpu information of the hosting server
      responses:
        '200':
          description: 'CPU info, or add more text'
